### ISSUE TITLE
Pre-build the container used for Flow deployments

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-dockerfiles#23]
When deploying Flow we _build_ a container on each execution. By _caching_ it we open the possibility of using it in a k8s Job

**Comment by dlebrero** [comment]
I am curious, cron job for what?

**Comment by iperdomo** [comment]
A `Job` not a `CronJob`.. The current deployment process is dominated by network traffic uploading files to a bucket. A developer deploying to 100+ instances needs to have a good network connection and _wait_ for the job to complete. The idea is to deploy by starting a `Job` in the `test` cluster and come back later for the result.
